///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c413839f-357d-4623-8b3f-a49797370cdd")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.ITResourcesCreamosExperienciasMasAppFolder _itresourcescreamosexperienciasmas;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("c413839f-357d-4623-8b3f-a49797370cdd")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "c413839f-357d-4623-8b3f-a49797370cdd", ".\\RepositoryImages\\MyTestRepositoryc413839f.rximgres")
        {
            _itresourcescreamosexperienciasmas = new MyTestRepositoryFolders.ITResourcesCreamosExperienciasMasAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c413839f-357d-4623-8b3f-a49797370cdd")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ITResourcesCreamosExperienciasMas folder.
        /// </summary>
        [RepositoryFolder("b7bc8e85-3a6b-4970-ae4c-c00f229e6424")]
        public virtual MyTestRepositoryFolders.ITResourcesCreamosExperienciasMasAppFolder ITResourcesCreamosExperienciasMas
        {
            get { return _itresourcescreamosexperienciasmas; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The ITResourcesCreamosExperienciasMasAppFolder folder.
        /// </summary>
        [RepositoryFolder("b7bc8e85-3a6b-4970-ae4c-c00f229e6424")]
        public partial class ITResourcesCreamosExperienciasMasAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _httpwwwsomositrcomimgitrlogosvgInfo;
            RepoItemInfo _serviciosdeitrInfo;
            RepoItemInfo _serviciosInfo;
            RepoItemInfo _designthinkingInfo;
            RepoItemInfo _qaqcInfo;
            RepoItemInfo _testingInfo;
            RepoItemInfo _testingautomatizadoInfo;
            RepoItemInfo _httpsomositrcomimgitrlogosvgInfo;
            RepoItemInfo _burgernavbarburgerInfo;
            RepoItemInfo _calidadeintegridaddenuestrosdesarroInfo;
            RepoItemInfo _imgtagimgicontestingautomatizadosInfo;

            /// <summary>
            /// Creates a new ITResourcesCreamosExperienciasMas  folder.
            /// </summary>
            public ITResourcesCreamosExperienciasMasAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ITResourcesCreamosExperienciasMas", "/dom[@domain~'somositr.com']", parentFolder, 30000, null, false, "b7bc8e85-3a6b-4970-ae4c-c00f229e6424", "")
            {
                _httpwwwsomositrcomimgitrlogosvgInfo = new RepoItemInfo(this, "HttpWwwSomositrComImgItrLogoSvg", "?/?/nav/?/?/a[@href='http://www.somositr.com/']/img[@src='http://www.somositr.com/img/itr-logo.svg']", 30000, null, "9de8695b-e4d7-431b-8d0f-7f74b453093c");
                _serviciosdeitrInfo = new RepoItemInfo(this, "ServiciosDeITR", ".//div[#'navbarBasicExample']/div/div[1]/?/?/a[@innertext='Servicios']", 30000, null, "56e357bb-4d64-4412-8f3c-74f4c8ee117b");
                _serviciosInfo = new RepoItemInfo(this, "Servicios", "body/section[1]/div//h1[@innertext='Servicios']", 30000, null, "ce901290-b4d9-4cdd-8503-3af86d7f46c6");
                _designthinkingInfo = new RepoItemInfo(this, "DesignThinking", ".//div[#'servicios']/div/div/div[4]//a[@href>'http://www.somositr.com/t']/div/div[1]/?/?/img[@alt='Design Thinking']", 30000, null, "0869bde5-99e3-4ce9-b0ab-4221640b377a");
                _qaqcInfo = new RepoItemInfo(this, "QAQC", ".//div[#'servicios']/div/div/div[4]//a[@href>'http://www.somositr.com/t']/div/div[2]/h4[@innertext='QA/QC']", 30000, null, "973fe36f-d88e-4c9d-a656-c0e681ca994f");
                _testingInfo = new RepoItemInfo(this, "Testing", "body/section[1]/div//h1[@innertext='Testing']", 30000, null, "47fe7467-77ea-4cc1-ab50-54a8d622e76c");
                _testingautomatizadoInfo = new RepoItemInfo(this, "TestingAutomatizado", "body//h4[@innertext='Testing automatizado']", 30000, null, "6a5d5f53-b992-48f6-9855-7f686d26a41b");
                _httpsomositrcomimgitrlogosvgInfo = new RepoItemInfo(this, "HttpSomositrComImgItrLogoSvg", "body/nav//img[@src='http://www.somositr.com/img/itr-logo.svg']", 30000, null, "19b30549-3b5c-4c8e-80c6-d01376d06605");
                _burgernavbarburgerInfo = new RepoItemInfo(this, "BurgerNavbarBurger", "?/?/nav/div[1]/a[@class='navbar-burger burger']", 30000, null, "f55311e7-b821-41ba-ac9c-92ee9a5a4590");
                _calidadeintegridaddenuestrosdesarroInfo = new RepoItemInfo(this, "CalidadEIntegridadDeNuestrosDesarro", ".//div[#'navbarBasicExample']/div/div[1]/?/?/a[@innertext='Testing']", 30000, null, "2b9f9a49-19a7-4f1f-9586-04b4e970efef");
                _imgtagimgicontestingautomatizadosInfo = new RepoItemInfo(this, "ImgTagImgIconTestingAutomatizadoS", "body//img[@alt>'../img/icon/testing/autom']", 30000, null, "b375dcc5-9030-494f-a9c4-15d5e1efc0fa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b7bc8e85-3a6b-4970-ae4c-c00f229e6424")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b7bc8e85-3a6b-4970-ae4c-c00f229e6424")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HttpWwwSomositrComImgItrLogoSvg item.
            /// </summary>
            [RepositoryItem("9de8695b-e4d7-431b-8d0f-7f74b453093c")]
            public virtual Ranorex.ImgTag HttpWwwSomositrComImgItrLogoSvg
            {
                get
                {
                    return _httpwwwsomositrcomimgitrlogosvgInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpWwwSomositrComImgItrLogoSvg item info.
            /// </summary>
            [RepositoryItemInfo("9de8695b-e4d7-431b-8d0f-7f74b453093c")]
            public virtual RepoItemInfo HttpWwwSomositrComImgItrLogoSvgInfo
            {
                get
                {
                    return _httpwwwsomositrcomimgitrlogosvgInfo;
                }
            }

            /// <summary>
            /// The ServiciosDeITR item.
            /// </summary>
            [RepositoryItem("56e357bb-4d64-4412-8f3c-74f4c8ee117b")]
            public virtual Ranorex.ATag ServiciosDeITR
            {
                get
                {
                    return _serviciosdeitrInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ServiciosDeITR item info.
            /// </summary>
            [RepositoryItemInfo("56e357bb-4d64-4412-8f3c-74f4c8ee117b")]
            public virtual RepoItemInfo ServiciosDeITRInfo
            {
                get
                {
                    return _serviciosdeitrInfo;
                }
            }

            /// <summary>
            /// The Servicios item.
            /// </summary>
            [RepositoryItem("ce901290-b4d9-4cdd-8503-3af86d7f46c6")]
            public virtual Ranorex.H1Tag Servicios
            {
                get
                {
                    return _serviciosInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The Servicios item info.
            /// </summary>
            [RepositoryItemInfo("ce901290-b4d9-4cdd-8503-3af86d7f46c6")]
            public virtual RepoItemInfo ServiciosInfo
            {
                get
                {
                    return _serviciosInfo;
                }
            }

            /// <summary>
            /// The DesignThinking item.
            /// </summary>
            [RepositoryItem("0869bde5-99e3-4ce9-b0ab-4221640b377a")]
            public virtual Ranorex.ImgTag DesignThinking
            {
                get
                {
                    return _designthinkingInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The DesignThinking item info.
            /// </summary>
            [RepositoryItemInfo("0869bde5-99e3-4ce9-b0ab-4221640b377a")]
            public virtual RepoItemInfo DesignThinkingInfo
            {
                get
                {
                    return _designthinkingInfo;
                }
            }

            /// <summary>
            /// The QAQC item.
            /// </summary>
            [RepositoryItem("973fe36f-d88e-4c9d-a656-c0e681ca994f")]
            public virtual Ranorex.H4Tag QAQC
            {
                get
                {
                    return _qaqcInfo.CreateAdapter<Ranorex.H4Tag>(true);
                }
            }

            /// <summary>
            /// The QAQC item info.
            /// </summary>
            [RepositoryItemInfo("973fe36f-d88e-4c9d-a656-c0e681ca994f")]
            public virtual RepoItemInfo QAQCInfo
            {
                get
                {
                    return _qaqcInfo;
                }
            }

            /// <summary>
            /// The Testing item.
            /// </summary>
            [RepositoryItem("47fe7467-77ea-4cc1-ab50-54a8d622e76c")]
            public virtual Ranorex.H1Tag Testing
            {
                get
                {
                    return _testingInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The Testing item info.
            /// </summary>
            [RepositoryItemInfo("47fe7467-77ea-4cc1-ab50-54a8d622e76c")]
            public virtual RepoItemInfo TestingInfo
            {
                get
                {
                    return _testingInfo;
                }
            }

            /// <summary>
            /// The TestingAutomatizado item.
            /// </summary>
            [RepositoryItem("6a5d5f53-b992-48f6-9855-7f686d26a41b")]
            public virtual Ranorex.H4Tag TestingAutomatizado
            {
                get
                {
                    return _testingautomatizadoInfo.CreateAdapter<Ranorex.H4Tag>(true);
                }
            }

            /// <summary>
            /// The TestingAutomatizado item info.
            /// </summary>
            [RepositoryItemInfo("6a5d5f53-b992-48f6-9855-7f686d26a41b")]
            public virtual RepoItemInfo TestingAutomatizadoInfo
            {
                get
                {
                    return _testingautomatizadoInfo;
                }
            }

            /// <summary>
            /// The HttpSomositrComImgItrLogoSvg item.
            /// </summary>
            [RepositoryItem("19b30549-3b5c-4c8e-80c6-d01376d06605")]
            public virtual Ranorex.ImgTag HttpSomositrComImgItrLogoSvg
            {
                get
                {
                    return _httpsomositrcomimgitrlogosvgInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The HttpSomositrComImgItrLogoSvg item info.
            /// </summary>
            [RepositoryItemInfo("19b30549-3b5c-4c8e-80c6-d01376d06605")]
            public virtual RepoItemInfo HttpSomositrComImgItrLogoSvgInfo
            {
                get
                {
                    return _httpsomositrcomimgitrlogosvgInfo;
                }
            }

            /// <summary>
            /// The BurgerNavbarBurger item.
            /// </summary>
            [RepositoryItem("f55311e7-b821-41ba-ac9c-92ee9a5a4590")]
            public virtual Ranorex.ATag BurgerNavbarBurger
            {
                get
                {
                    return _burgernavbarburgerInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The BurgerNavbarBurger item info.
            /// </summary>
            [RepositoryItemInfo("f55311e7-b821-41ba-ac9c-92ee9a5a4590")]
            public virtual RepoItemInfo BurgerNavbarBurgerInfo
            {
                get
                {
                    return _burgernavbarburgerInfo;
                }
            }

            /// <summary>
            /// The CalidadEIntegridadDeNuestrosDesarro item.
            /// </summary>
            [RepositoryItem("2b9f9a49-19a7-4f1f-9586-04b4e970efef")]
            public virtual Ranorex.ATag CalidadEIntegridadDeNuestrosDesarro
            {
                get
                {
                    return _calidadeintegridaddenuestrosdesarroInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The CalidadEIntegridadDeNuestrosDesarro item info.
            /// </summary>
            [RepositoryItemInfo("2b9f9a49-19a7-4f1f-9586-04b4e970efef")]
            public virtual RepoItemInfo CalidadEIntegridadDeNuestrosDesarroInfo
            {
                get
                {
                    return _calidadeintegridaddenuestrosdesarroInfo;
                }
            }

            /// <summary>
            /// The ImgTagImgIconTestingAutomatizadoS item.
            /// </summary>
            [RepositoryItem("b375dcc5-9030-494f-a9c4-15d5e1efc0fa")]
            public virtual Ranorex.ImgTag ImgTagImgIconTestingAutomatizadoS
            {
                get
                {
                    return _imgtagimgicontestingautomatizadosInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The ImgTagImgIconTestingAutomatizadoS item info.
            /// </summary>
            [RepositoryItemInfo("b375dcc5-9030-494f-a9c4-15d5e1efc0fa")]
            public virtual RepoItemInfo ImgTagImgIconTestingAutomatizadoSInfo
            {
                get
                {
                    return _imgtagimgicontestingautomatizadosInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
