///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SetMobileView()
        {
            //Variables
            string endpoint = string.Empty;
            string config = string.Empty;
            
            try {
            	endpoint = Host.Current.TryGetAsWebDriverEndpoint().DisplayName.ToString();
            	config = Host.Current.TryGetAsWebDriverEndpoint().CurrentConfiguration.ToString();
            } catch (Exception) {
            	endpoint = "LOCAL";
            }
            
            
            if (endpoint == "LOCAL")
            {
            	Keyboard.Press("{F12}");
            	Report.Info("INFO","Ejecucion local, se presiona la tecla F12 para el modo mobile del browser");
            } else {
            	Report.Info("INFO","Se realiza la ejecucion en el endpoint: " + endpoint + " con la configuracion: " + config);
            }
            	
            		
        }

    }
}
